### ISSUE TITLE
Is it possible to translate an onnx model into onnxscript?

### ISSUE THREAD

**Issue by kailums** [microsoft/onnxscript#952]
Hi guys.

It's difficult for us to do operation fusion on onnx model, because we need to look into the model, identify the pattern and match the pattern exactly for fusion. when the model changes slightly, the pattern can't match, then we failed to fuse the op. And also this process takes more effects.

Here i got an idea. If we can translate an onnx model into onnxscript, then we can modify the script, fuse some ops into function just using python. it will more efficient.

**Comment by gramalingam** [comment]
Yes, there is already a preliminary version of an "onnx model to onnxscript" converter, namely `onnxscript.proto2python` (which is an alias for [export2python](https://github.com/microsoft/onnxscript/blob/3c0c7a8e5b7b9273d755b37ecd47f59cd79b4536/onnxscript/backend/onnx_export.py#L525)

I am a bit confused, however, as to whether you are trying to do fusion automatically or manually. When you mention the pattern-matcher, it looks like an automated onnx optimizer. But if you convert it to onnxscript, do you plan to edit it manually?

**Comment by kailums** [comment]
yes, I want to modify the model manually.

I am trying to fuse rotary_embedding in llamav2 model. At first i want to write a pattern matcher like onnxruntime's transformer optimizer to fuse this op.

but i found the structure it too complex to match, part of it looks like this:
![image](https://github.com/microsoft/onnxscript/assets/109063327/9d51cfad-a084-485b-a7ed-26be3a5df579)

so i think it may be more easier for me to convert this model into onnxscript, and directly modify it to a fused onnx function.

**Comment by gramalingam** [comment]
Please try `onnxscript.proto2python(model, use_operators=True, inline_const=True)`. The options generate more readable encodings.

I would also recommend converting the model to use external_data, because there isn't a convenient way of encoding large tensors in text-form in onnxscript. If the model already uses external_data, use the `load_external_data=False` when you load the model.

If the model doesn't use external_data, you can first convert it to external_data format via
```py
onnx.save(model, modelfile, save_as_external_data=True, all_tensors_to_one_file=True, size_threshold=64, convert_attribute=True, location=datafile)
```

But the conversion from onnx to onnxscript is still experimental. If you run into any issues, please do let us know, thanks!

**Comment by kailums** [comment]
Thanks @gramalingam

**Comment by gramalingam** [comment]
> 2\. the variable name 'transformer.block_list.0.attn_norm.weight' is not valid

Right, I ran into this yesterday while trying it out. It's already been fixed in this PR: https://github.com/microsoft/onnxscript/pull/956 

Not sure about the missing bracket. If you have a model to share, I'd appreciate that, I can work on fixing it, thanks!

**Comment by kailums** [comment]
yes, you can use this llamav2 model: [https://github.com/microsoft/Llama-2-Onnx-7-FT-16](https://github.com/microsoft/Llama-2-Onnx-7-FT-16)

```
import onnx
from onnxscript import proto2python


onnx_model_file = './Llama-2-Onnx-7-FT-16/ONNX/LlamaV2_7B_FT_float16.onnx'


onnx_model = onnx.load(onnx_model_file, load_external_data=False)

code = proto2python(onnx_model, use_operators=True, inline_const=True)

with open('llamav2-7b-model.py', 'w') as fp:
    fp.write(code)
```

**Comment by BowenBao** [comment]
> but i found the structure it too complex to match, part of it looks like this:

The latest [dynamo onnx exporter](https://pytorch.org/docs/master/onnx.html#preview-torch-onnx-torchdynamo-exporter) should greatly help with this as it keeps `nn.Module` calls as functions in onnx model.

cc @kunal-vaishnavi

**Comment by akashmjn** [comment]
Strong +1 on this request! 

Small differences from HuggingFace implementations used by the `optimizer` tool require digging into gnarly operator fusion pattern matching to use ops like [`MultiHeadAttention`](https://github.com/microsoft/onnxruntime/blob/4324d2173b44eda7967ee2348af7c9134f8c1350/onnxruntime/python/tools/transformers/fusion_bart_attention.py). This is brittle, hard to maintain and honestly feels like a needlessly roundabout approach if you know you want to use this op in a particular place. 

Either of these two would be very welcome:
- Directly authoring a full model in ONNXScript as in https://github.com/microsoft/onnxscript/issues/820. User has full control on using the best fused ops. Even if this means a separate file from one's pytorch training code, this is far more readable and maintainable. Implementing a full transformer by hand is much less code than pattern matching.
- Loading a pre-existing ONNX model into ONNXScript and then rewriting code instead of graph pattern-matching as suggested by @kailums

**Comment by justinchuby** [comment]
Thanks - we are looking to make (2) as well as pattern matching much easier. (1) is also possible with the up coming tracing support.

**Comment by norlesh** [comment]
In the landing page of [onnxscript.ai](http://onxscript.ai) in the overview section it includes the statement 

> A converter that translates ONNX models and functions into ONNX Script. This capability can be used to fully round-trip ONNX Script ↔ ONNX graph.

Yet it took me around an hour to eventually find this thread as the only clue so far as to how to achieve this!

**Comment by titaiwangms** [comment]
Feel free to reopen if the question is not answered.

**Comment by justinchuby** [comment]
@Stonesjtu Please take a look at https://github.com/onnx/ir-py
